baseurl = "https://www.eclipse.org/pdt"
DefaultContentLanguage = "en"
title = "Eclipse PHP Development Tools"
theme = "hugo-solstice-theme"
metaDataFormat = "yaml"
disableKinds = []
enableRobotsTXT = true
pluralizeListTitles = false

[Params]
  google_tag_manager = "GTM-5WLCZXC"
  description = "The Eclipse Foundation provides our global community of individuals and organizations with a mature, scalable, and business-friendly environment for open source software collaboration and innovation."
  seo_title_suffix = " | The Eclipse Foundation"
  keywords = ["eclipse", "project", "plug-ins", "plugins", "java", "ide", "swt", "refactoring", "PHP", "tool", "web", "editor", "composer", "debuger", "profiler", "phpunit", "xdebug"]
  news_count = 3
  gcse = "011805775785170369411:p3ec0igo0qq"
  gcse_result_url = "https://www.eclipse.org/home/search/"
  header_wrapper_class = "header_wrapper_class"
  call_for_action_text = "Download"
  call_for_action_url = "//eclipse.org/downloads/"
  call_for_action_icon = "fa-download"
  layout_style = "astro"
  hide_ad = false
  featured_content_publish_target = "eclipse_org"
  sidebar_layout = "sidebar_block"
  eclipse_version = "2025-06"
  latest = "8.3"
  latest_dev = "8.4"


# js = ""
# styles = ""
# logo = ""
# favicon = ""
# share_img = ""
# logo_width = ""
# header_left_classes = ""
# main_menu_wrapper_classes = ""
# projects_working_group = ""
# show_events = true
# table_classes = "table table-bordered"
# hide_cfa_same_page = true
# show_collapsible_menu = true

[taxonomies]
  tag = "tags"

[Params.author]
  name = "Eclipse PDT Team"
  website = "https://www.eclipse.org/pdt"
  email = "pdt-dev@eclipse.org"
  facebook = "eclipse.org"
  twitter = "eclipsefdn"
  youtube = "EclipseFdn"
  googleplus = "+Eclipse"
  linkedin = "company/eclipse-foundation/"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[[menu.sidebar]]
  name = "Menu2"
  url = ""
  weight = 1
  identifier = "home2"

[[menu.sidebar]]
  name = ""
  url = ""
  weight = 2
  identifier = "home"
  
[[menu.sidebar]]
  parent ="home"
  name = "Repository & Issues"
  url = "https://github.com/eclipse-pdt/pdt"
  weight = 1
  pre = "<i class=\"sidebar-menu-icon\" data-feather=\"github\"></i>"

[[menu.sidebar]]
  parent = "home"
  name = "Menu"
  url = ""
  weight = 2
  identifier = "menu"
  pre = "<i class=\"sidebar-menu-icon\" data-feather=\"menu\"></i>"
  


[[menu.sidebar]]
  parent ="menu"
  name = "About"
  url = "#about"
  weight = 1


[[menu.sidebar]]
  parent ="menu"
  name = "Features"
  url = "#features"
  weight = 2
  

[[menu.sidebar]]
  parent ="menu"
  name = "Download"
  url = "#download"
  weight = 3

[[menu.sidebar]]
  parent ="menu"
  name = "Extensions"
  url = "#extensions"
  weight = 4

[[menu.sidebar]]
  parent =" menu"
  name = "Contributing"
  url = "#contributing"
  weight = 5

[[menu.sidebar]]
  name = "Project"
  parent = "home"
  url = ""
  weight = 2
  identifier = "project"
  pre = "<i class=\"sidebar-menu-icon\" data-feather=\"activity\"></i>"
[[menu.sidebar]]
  parent ="project"
  name = "News & Noteworthy"
  url = "https://github.com/eclipse-pdt/pdt/wiki/NewIn83"
  weight = 1
[[menu.sidebar]]
  parent ="project"
  name = "Marketplace"
  url = "https://marketplace.eclipse.org/content/php-development-tools"
  weight = 2
[[menu.sidebar]]
  parent ="project"
  name = "Project Details"
  url = "https://projects.eclipse.org/projects/tools.pdt/"
  weight = 4
[[menu.sidebar]]
  parent ="project"
  name = "Repository"
  url = "https://github.com/eclipse-pdt/pdt"
  weight = 5
[[menu.sidebar]]
  name = "Support"
  parent = "home"
  url = ""
  weight = 8
  identifier = "support"
  pre = "<i class=\"sidebar-menu-icon\" data-feather=\"help-circle\"></i>"
[[menu.sidebar]]
  name = "Manual"
  parent = "support"
  url = "https://help.eclipse.org/topic/org.eclipse.php.help/html/table_of_contents.html"
  weight = 1
[[menu.sidebar]]
  name = "Forum"
  parent = "support"
  url = "https://www.eclipse.org/forums/index.php/f/85/"
  weight = 2
[[menu.sidebar]]
  name = "Wiki"
  parent = "support"
  url = "https://github.com/eclipse-pdt/pdt/wiki"
  weight = 3
[[menu.sidebar]]
  name = "Mailing list"
  parent = "support"
  url = "https://dev.eclipse.org/mailman/listinfo/pdt-dev"
  weight = 4
[[menu.sidebar]]
  name = "Submit a bug"
  parent = "support"
  url = "https://github.com/eclipse-pdt/pdt/issues/new?assignees=&labels=bug&template=bug_report.md&title="
  weight = 5

# Uncomment [[menu.main]] to hide the default EF menu
# or to define your own menu links.

# [[menu.main]]
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[security]
      enableInlineShortcodes = true